#!/bin/bash

# This script generates a system report containing various information about the system.
# It includes system information such as hostname, OS, and uptime, hardware information like CPU, RAM, and disks,
# network information including FQDN, IP address, and DNS server, system status such as logged-in users, disk space,
# and process count, and UFW rules if enabled.

# System Information
HOSTNAME=$(hostname)                            # Get the hostname of the system
DISTRO=$(source /etc/os-release && echo $PRETTY_NAME)  # Get the distribution name and version
UPTIME=$(uptime -p)                             # Get the uptime of the system

# Hardware Information
CPU=$(lshw -c cpu | awk '/product/ {print $2" "$3}')     # Get CPU make and model
CPU_SPEED=$(lscpu | awk '/^CPU MHz/ {print $3}' | sort -rn | head -n1)  # Get current CPU speed
MAX_CPU_SPEED=$(lscpu | awk '/^CPU max MHz/ {print $4}')  # Get maximum CPU speed
RAM=$(free -h | awk '/Mem/ {print $2}')           # Get installed RAM size
DISKS=$(lsblk -o NAME,MODEL,SIZE | awk '{if (NR>1) print $2" "$3" "$4}')  # Get disk information
VIDEO=$(lshw -c video | awk '/product/ {print $2" "$3}')  # Get video card make and model

# Network Information
FQDN=$(hostname -f)                            # Get the fully qualified domain name
HOST_IP=$(hostname -I | awk '{print $1}')      # Get the host IP address
GATEWAY_IP=$(ip r | awk '/default/ {print $3}')   # Get the gateway IP address
DNS_SERVER=$(grep nameserver /etc/resolv.conf | awk '{print $2}')  # Get the DNS server IP address
INTERFACE=$(lshw -c network | awk '/logical name/ {print $3}' | head -n1)  # Get network interface name
IP_ADDRESS=$(ip a show $INTERFACE | awk '/inet/ {print $2}')  # Get IP address of the network interface

# System Status
USERS=$(who | awk '{print $1}' | sort -u | tr '\n' ',')  # Get currently logged in users
USERS=${USERS%,}                              # Remove trailing comma
DISK_SPACE=$(df -h | awk '/^\/dev/ {print $1" "$4}')    # Get free disk space
PROCESS_COUNT=$(ps -ef | wc -l)                    # Get process count
LOAD_AVERAGES=$(uptime | awk -F'[a-z]:' '{print $2}')    # Get load averages
MEMORY_ALLOCATION=$(free -h | awk '/Mem/ {print "Total: "$2", Used: "$3", Free: "$4}')  # Get memory allocation
LISTENING_PORTS=$(ss -lntu | awk 'NR>1 {print $5}' | cut -d: -f2 | sort -u | tr '\n' ',') # Get listening network ports
LISTENING_PORTS=${LISTENING_PORTS%,}                   # Remove trailing comma
UFW_RULES=$(sudo ufw status numbered | awk '{print $2" "$3" "$4" "$5" "$6}')  # Get UFW rules

# Output
cat <<EOF

System Report generated by $USER, $(date +"%Y-%m-%d %H:%M:%S")

System Information
------------------
Hostname: $HOSTNAME                         # Display hostname
OS: $DISTRO                               # Display OS information
Uptime: $UPTIME                            # Display system uptime

Hardware Information
--------------------
CPU: $CPU                                 # Display CPU information
Speed: $CPU_SPEED MHz (Max: $MAX_CPU_SPEED MHz)   # Display CPU speed
RAM: $RAM                                 # Display RAM information
Disk(s): $DISKS                            # Display disk information
Video: $VIDEO                              # Display video card information

Network Information
-------------------
FQDN: $FQDN                               # Display fully qualified domain name
Host Address: $HOST_IP                       # Display host IP address
Gateway IP: $GATEWAY_IP                      # Display gateway IP address
DNS Server: $DNS_SERVER                      # Display DNS server IP address

Interface: $INTERFACE                        # Display network interface
IP Address: $IP_ADDRESS                      # Display IP address of the network interface

System Status
-------------
Users Logged In: $USERS                     # Display logged-in users
Disk Space: $DISK_SPACE                     # Display disk space information
Process Count: $PROCESS_COUNT                # Display process count
Load Averages: $LOAD_AVERAGES                # Display load averages
Memory Allocation: $MEMORY_ALLOCATION          # Display memory allocation
Listening Network Ports: $LISTENING_PORTS           # Display listening network ports
UFW Rules: $UFW_RULES                       # Display UFW rules

EOF
