#!/bin/bash

# System Information
HOSTNAME=$(hostname)
DISTRO=$(source /etc/os-release && echo $PRETTY_NAME)
UPTIME=$(uptime -p)

# Hardware Information
CPU=$(lshw -c cpu | awk '/product/ {print $2" "$3}')
CPU_SPEED=$(lscpu | awk '/^CPU MHz/ {print $3}' | sort -rn | head -n1)
MAX_CPU_SPEED=$(lscpu | awk '/^CPU max MHz/ {print $4}')
RAM=$(free -h | awk '/Mem/ {print $2}')
DISKS=$(lsblk -o NAME,MODEL,SIZE | awk '{if (NR>1) print $2" "$3" "$4}')
VIDEO=$(lshw -c video | awk '/product/ {print $2" "$3}')

# Network Information
FQDN=$(hostname -f)
HOST_IP=$(hostname -I | awk '{print $1}')
GATEWAY_IP=$(ip r | awk '/default/ {print $3}')
DNS_SERVER=$(grep nameserver /etc/resolv.conf | awk '{print $2}')
INTERFACE=$(lshw -c network | awk '/logical name/ {print $3}' | head -n1)
IP_ADDRESS=$(ip a show $INTERFACE | awk '/inet/ {print $2}')

# System Status
USERS=$(who | awk '{print $1}' | sort -u | tr '\n' ',')
USERS=${USERS%,} # remove trailing comma
DISK_SPACE=$(df -h | awk '/^\/dev/ {print $1" "$4}')
PROCESS_COUNT=$(ps -ef | wc -l)
LOAD_AVERAGES=$(uptime | awk -F'[a-z]:' '{print $2}')
MEMORY_ALLOCATION=$(free -h | awk '/Mem/ {print "Total: "$2", Used: "$3", Free: "$4}')
LISTENING_PORTS=$(ss -lntu | awk 'NR>1 {print $5}' | cut -d: -f2 | sort -u | tr '\n' ',')
LISTENING_PORTS=${LISTENING_PORTS%,} # remove trailing comma
UFW_RULES=$(sudo ufw status numbered | awk '{print $2" "$3" "$4" "$5" "$6}')

# Output
cat <<EOF

System Report generated by $USER, $(date +"%Y-%m-%d %H:%M:%S")

System Information
------------------
Hostname: $HOSTNAME
OS: $DISTRO
Uptime: $UPTIME

Hardware Information
--------------------
CPU: $CPU
Speed: $CPU_SPEED MHz (Max: $MAX_CPU_SPEED MHz)
RAM: $RAM
Disk(s): $DISKS
Video: $VIDEO

Network Information
-------------------
FQDN: $FQDN
Host Address: $HOST_IP
Gateway IP: $GATEWAY_IP
DNS Server: $DNS_SERVER

Interface: $INTERFACE
IP Address: $IP_ADDRESS

System Status
-------------
Users Logged In: $USERS
Disk Space: $DISK_SPACE
Process Count: $PROCESS_COUNT
Load Averages: $LOAD_AVERAGES
Memory Allocation: $MEMORY_ALLOCATION
Listening Network Ports: $LISTENING_PORTS
UFW Rules: $UFW_RULES

EOF
